### ISSUE TITLE
 Timer restart button, Timer flags, Timer Stop button

### ISSUE THREAD

**Issue by CuvetteTA** [CuvetteTA/superapp#6]
- [x]  Timer restart button
- [x]  Timer Stop button
- [x]  Timer flags (customize the chronograph to show lines or similar flags)

**Comment by RatneshMaurya1** [comment]
please assign this task to me

**Comment by CuvetteTA** [comment]
@RatneshMaurya1 you can try it out, Send the ss of your final and previous content when done

**Comment by CuvetteTA** [comment]
This Issue was closed. Well done @RatneshMaurya1.
